spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_manager?createDatabaseIfNotExist=true
    password: Ravi@12345    
    username: root
  jpa:
    #hibernate:
      #ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    